version: 0.0
os: linux

files:
  - source: aparttime-admin.jar
    destination: /home/ec2-user/app
    overwrite: yes


hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 30
      runas: ec2-user

    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user