version: 0.0
os: linux

files:
  - source: app.jar
    destination: /home/ec2-user/app

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: ec2-user

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user