name: Deploy Spring Boot to EC2

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: ap-northeast-2
  JAR_NAME: aparttime-admin-server-0.0.1-SNAPSHOT.jar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Make deployment package
        run: |
          mkdir -p deploy
          cp build/libs/${{ env.JAR_NAME }} deploy/aparttime-admin.jar
          cp appspec.yml deploy/
          cp -r scripts/ deploy/
          chmod +x deploy/scripts/*.sh
          cd deploy && zip -r deploy.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp deploy/deploy.zip s3://${{ secrets.AWS_S3_BUCKET }}/deployments/backend/deploy.zip

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
            --deployment-group-name ${{ secrets.CODEDEPLOY_GROUP_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},key=deployments/backend/deploy.zip,bundleType=zip